name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  choco-dir: ./choco/
  src-dir: ./src/
  out-dir: ./out/
  artifacts-dir: ./artifacts/

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3
      with:
          versionSpec: '5.2.x'
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ env.src-dir }}
    - name: Publish
      run: dotnet publish -o "../${{ env.out-dir }}" -c Release --self-contained false --no-restore
      working-directory: ${{ env.src-dir }}
    - name: Versioning
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3
    - name: Create directory
      run: |
        md -Force ${{ env.artifacts-dir }}
      shell: pwsh
    - name: Zip
      run: |
        Compress-Archive -Path ${{ env.out-dir }}/* -DestinationPath ${{ env.artifacts-dir }}giti-${{ steps.gitversion.outputs.fullSemVer }}.zip
      shell: pwsh
    - name: Package
      run: |
        choco pack --version ${{ steps.gitversion.outputs.semVer }}
        Copy-Item *.nupkg "../${{ env.artifacts-dir }}"
      working-directory: ${{ env.choco-dir }}
      shell: pwsh
    - name: Release Github
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        files: "${{ env.choco-dir }}/*"
        name: ${{ steps.gitversion.outputs.fullSemVer }}  
        tag_name: ${{ steps.gitversion.outputs.fullSemVer }}
    - name: Release Chocolatey
      # if: startsWith(github.ref, 'refs/tags/')
      run: |
        choco apikey -k ${{ secrets.CHOCO_APIKEY }} -s https://push.chocolatey.org/
        choco push -s https://push.chocolatey.org/
      shell: pwsh
      working-directory: ${{ env.choco-dir }}
